# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 909456f30d2887da0f2400ca4c5d3489df71e4a096c2198d36c1c276ee5d0d0f6053d8f07d53979608ac834f4628c5ebddb901442f5e58e32058d514abebdd67

test:
  secret_key_base: 27950f116ee4141ee99a5c61da2a3bf5a127d1db5d7713fda92eacab9c1519cd63d08df4a9e7ddb309149534fee75925b66d5c0719a6ecc15e8fcd86ce7353b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
