---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 707986125747593216-MQNAflZ7tRRngB10l9X4ZuGSebWQTl5
:access_token_secret: b24ytZYoExD0gJTr8fCuuc7PobounmP8Jmj3NipKCtoXB
